acmeair-bloat-db:
  container_name: acmeair-bloat-db
  image: mongo
  net: ${NETWORK}

acmeair-booking-db:
  container_name: acmeair-booking-db
  image: mongo
  net: ${NETWORK}

acmeair-customer-db:
  container_name: acmeair-customer-db
  image: mongo
  net: ${NETWORK}

acmeair-flight-db:
  container_name: acmeair-flight-db
  image: mongo
  net: ${NETWORK}

acmeair-reward-db:
  container_name: acmeair-reward-db
  image: mongo
  net: ${NETWORK}

acmeair-nginx1:
  container_name: acmeair-nginx1
  net: ${NETWORK}
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - acmeair-mainservice-java
    - acmeair-authservice-java
    - acmeair-bloatservice-java
    - acmeair-bookingservice-java
    - acmeair-customerservice-java
    - acmeair-flightservice-java
    - acmeair-rewardservice-java

acmeair-mainservice-java:
  container_name: acmeair-mainservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-mainservice-java/
  environment:
    - LICENSE=accept
  mem_limit: 512m

acmeair-bloatservice-java:
  container_name: acmeair-bloatservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-bloatservice-java/
  environment:
    - MONGO_HOST=acmeair-bloat-db
    - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
    - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
    - ACMEAIR_STACKAA_FLIGHT_URL=http://acmeair-nginx1/flight
  volumes_from:
    - acmeair-bloat-db
  mem_limit: 512m

#TODO: remove env variables and check if it works
acmeair-rewardservice-java:
  container_name: acmeair-rewardservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-rewardservice-java/
  environment:
    - MONGO_HOST=acmeair-reward-db
    - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
    - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
    - ACMEAIR_STACKAA_FLIGHT_URL=http://acmeair-nginx1/flight
  volumes_from:
    - acmeair-reward-db
  mem_limit: 512m

acmeair-authservice-java:
  container_name: acmeair-authservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-authservice-java/
  environment:
    - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
  mem_limit: 512m

acmeair-bookingservice-java:
  container_name: acmeair-bookingservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-bookingservice-java/
  environment:
    - MONGO_HOST=acmeair-booking-db
    - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
    - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
    - ACMEAIR_STACKAA_FLIGHT_URL=http://acmeair-nginx1/flight
    - ACMEAIR_STACKAA_REWARD_URL=http://acmeair-nginx1/reward
  volumes_from:
    - acmeair-booking-db
  mem_limit: 512m

acmeair-customerservice-java:
  container_name: acmeair-customerservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-customerservice-java/
  environment:
    - MONGO_HOST=acmeair-customer-db
    - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
  volumes_from:
    - acmeair-customer-db
  mem_limit: 512m

acmeair-flightservice-java:
  container_name: acmeair-flightservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-flightservice-java/
  environment:
    - MONGO_HOST=acmeair-flight-db
  volumes_from:
    - acmeair-flight-db
  mem_limit: 512m
