version: "3.8"

services:
  acmeair-booking-db:
    container_name: acmeair-booking-db
    image: mongo
    command: --replSet booking
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    networks:
      - acmeair

  acmeair-flight-db:
    container_name: acmeair-flight-db
    image: mongo
    networks:
      - acmeair

  acmeair-car-db:
    container_name: acmeair-car-db
    image: mongo
    networks:
      - acmeair

  acmeair-reward-db:
    container_name: acmeair-reward-db
    image: mongo
    networks:
      - acmeair

  acmeair-customer-db:
    container_name: acmeair-customer-db
    image: mongo
    command: --replSet customer
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    networks:
      - acmeair

  acmeair-nginx1:
    container_name: acmeair-nginx1
    networks:
      - acmeair
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/public
      - acmeair-mainservice-java
      - acmeair-authservice-java
      - acmeair-bookingservice-java
      - acmeair-customerservice-java
      - acmeair-flightservice-java
      - acmeair-carservice-java

  acmeair-rewardservice-java:
    container_name: acmeair-rewardservice-java
    networks:
      - acmeair
    build:
      dockerfile: Dockerfile
      context: ../acmeair-rewardservice-java/
    environment:
      - MONGO_HOST=acmeair-reward-db
    volumes:
      - acmeair-reward-db
    deploy:
      resources:
        limits:
          memory: 512m

  acmeair-mainservice-java:
    container_name: acmeair-mainservice-java
    networks:
      - acmeair
    build:
      dockerfile: Dockerfile
      context: ../acmeair-mainservice-java/
    environment:
      - LICENSE=accept
    deploy:
      resources:
        limits:
          memory: 512m

  acmeair-carservice-java:
    container_name: acmeair-carservice-java
    networks:
      - acmeair
    build:
      dockerfile: Dockerfile
      context: ../acmeair-carservice-java/
    environment:
      - MONGO_HOST=acmeair-car-db
    volumes:
      - acmeair-car-db
    deploy:
      resources:
        limits:
          memory: 512m

  acmeair-authservice-java:
    container_name: acmeair-authservice-java
    networks:
      - acmeair
    build:
      dockerfile: Dockerfile
      context: ../acmeair-authservice-java/
    environment:
      - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
    deploy:
      resources:
        limits:
          memory: 512m

  acmeair-bookingservice-java:
    container_name: acmeair-bookingservice-java
    networks:
      - acmeair
    build:
      dockerfile: Dockerfile
      context: ../acmeair-bookingservice-java/
    environment:
      - MONGO_HOST=acmeair-booking-db
      - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
      - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
      - ACMEAIR_STACKAA_FLIGHT_URL=http://acmeair-nginx1/flight
      - ACMEAIR_STACKAA_CAR_URL=http://acmeair-nginx1/car
      - ACMEAIR_STACKAA_REWARD_URL=http://acmeair-nginx1/reward
    volumes:
      - acmeair-booking-db
    deploy:
      resources:
        limits:
          memory: 512m

  acmeair-customerservice-java:
    container_name: acmeair-customerservice-java
    networks:
      - acmeair
    build:
      dockerfile: Dockerfile
      context: ../acmeair-customerservice-java/
    environment:
      - MONGO_HOST=acmeair-customer-db
      - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
      - ACMEAIR_STACKAA_BOOKING_URL=http://acmeair-nginx1/booking
    volumes:
      - acmeair-customer-db
    deploy:
      resources:
        limits:
          memory: 512m

  acmeair-flightservice-java:
    container_name: acmeair-flightservice-java
    networks:
      - acmeair
    build:
      dockerfile: Dockerfile
      context: ../acmeair-flightservice-java/
    environment:
      - MONGO_HOST=acmeair-flight-db
    volumes:
      - acmeair-flight-db
    deploy:
      resources:
        limits:
          memory: 512m

volumes:
  acmeair-mainservice-java:
  acmeair-authservice-java:
  acmeair-bookingservice-java:
  acmeair-customerservice-java:
  acmeair-flightservice-java:
  acmeair-carservice-java:

networks:
  acmeair:
